// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siunjhiiaduktoqjxalv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdW5qaGlpYWR1a3RvcWp4YWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzY3MTUsImV4cCI6MjA2MTMxMjcxNX0._AgD02DDc6E5gY0Hy4NPUZtRL_JVDiSiYcU2mwaWBoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);